# Generated by Django 3.2.9 on 2021-12-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='start_bid',
            new_name='current_price',
        ),
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
