# Generated by Django 3.2.9 on 2021-12-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211201_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('a', 'Electronics'), ('b', 'Collectibles & Art'), ('c', 'Fashion'), ('d', 'Motors'), ('e', 'Sporting Goods'), ('f', 'Health & Beauty'), ('g', 'Books, Movies & Music'), ('h', 'Business & Industrial'), ('i', 'Home & Garden'), ('j', 'Others')], default='Others', max_length=1),
        ),
    ]
