# Generated by Django 3.2.9 on 2021-12-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listings_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='listing_title',
            new_name='comment_title',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=300),
        ),
    ]
