# Generated by Django 3.2.9 on 2021-12-02 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='watchlist',
        ),
        migrations.CreateModel(
            name='Watchlists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(max_length=64, on_delete=django.db.models.deletion.CASCADE, related_name='user_watch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='bids', to='auctions.Watchlists'),
        ),
    ]
