# Generated by Django 3.2.9 on 2021-12-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20211202_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='watchlists',
        ),
        migrations.DeleteModel(
            name='Watchlists',
        ),
    ]
